name: Build project

on: [push]

jobs:
  buildForAndroid:
    name: Build for Android
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
       
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-Android
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: Android
      - uses: actions/upload-artifact@v2
        with:
          name: Build-Android
          path: build/Android
